### ISSUE TITLE
How to add a new ESP board?

### ISSUE THREAD

**Issue by angelbarusta** [esp8266/esp8266.github.io#10]
Hello, what are the requirements to add a new ESP board in the json file: **http://arduino.esp8266.com/stable/package_esp8266com_index.json,** so that it appears in the arduino IDE card manager?
example:
`"boards": [
{
"name": "My ESP8266 Module"
},]`

**Comment by earlephilhower** [comment]
Please use the https://github.com/esp8266/Arduino/ repo for these questions.

You're going to have to edit the tools/boards.txt.py script and regenerate the requisite files.  It's documented in the repo.
