### ISSUE TITLE
AT commands of ESP8266

### ISSUE THREAD

**Issue by Ann125** [esp8266/esp8266.github.io#2]
Hi all,
I am working on ESP8266 with arduino UNO. I have flashed new firmware into the ESP8266 module, after that when I opened the serial console of arduino only two AT commands are working which are AT and AT+GMR. When other AT commands are given, it shows an error.  Can anyone helps me to solve this.

Regards 
Ann

**Comment by igrr** [comment]
Sorry, not related to this repo...
