### ISSUE TITLE
JSON host is down

### ISSUE THREAD

**Issue by MichaelNZ404** [esp8266/esp8266.github.io#7]
A couple of guides for setting up the 8266 references the page http://arduino.esp8266.com/package_esp8266com_index.json, which is inaccessible.

**Comment by igrr** [comment]
I think `/stable/` is missing from the URL.

**Comment by MichaelNZ404** [comment]
Okay great, there's just a bad/legacy link on https://openhomeautomation.net/getting-started-esp8266. 
https://www.instructables.com/id/Get-Started-With-NodeMCU/ has the correct link and I was able to use the github link directly - so probably a non issue :)
