### ISSUE TITLE
problem adding to ide arduino

### ISSUE THREAD

**Issue by okpapt** [esp8266/esp8266.github.io#8]
Hello, sorry for my poor english.
I added 
https://github.com/esp8266/esp8266.github.io/blob/master/stable/package_esp8266com_index.json
but nothing new in ide.
I download 
https://github.com/esp8266/Arduino/releases/download/2.6.3/esp8266-2.6.3.zip
and can't add it by zip libraries.
Can you hep me or modify was wfrong in your file ?

**Comment by bakliwalp** [comment]
https://arduino.esp8266.com/stable/package_esp8266com_index.json

@okpapt add this link in file/preferences/additional url options. and you are set to go.
