### ISSUE TITLE
MacOS BigSur Error

### ISSUE THREAD

**Issue by VASAPOL** [esp8266/esp8266.github.io#9]
I have 2 Mac book and have same issue I tried to uploads sketch and it show

pyserial or esptool directories not found next to this upload.py tool.
An error occurred while uploading the sketch

I tried to reinstall esp8266 and issue found again please help.

Thank You

**Comment by gunterthomas** [comment]
Same here - won't work for me after Big Sur Update.

**Comment by earlephilhower** [comment]
Please open something on the Arduino repo about this.  This is the documentation repo and not monitored.

**Comment by hey-om7** [comment]
> Same here - won't work for me after Big Sur Update.

My side also same issue continues please help there is supposingly no solution i found on the internet
